version: '3.6'

services:
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-insights}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-insights}
      - POSTGRES_DB=${POSTGRES_DB:-insights}

  insights-indexer:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  es:
    image: elasticsearch:7.14.1
    container_name: indexer-es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "1"
          memory: 2G
    ports:
      - 9200:9200
    networks:
      - default
    volumes:
      - esdata:/usr/share/elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: indexer-kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    networks:
      - default

volumes:
  esdata:
    driver: local
